---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keep
resources:
- keep-namespace.yaml
- keep-helmrepository.yaml
- keep-helmrelease.yaml
- keep-ingress.yaml
- keep-networkpolicy.yaml
