---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
- otel-demo-namespace.yaml
- otel-demo-helmrepository.yaml
- otel-demo-helmrelease.yaml
- otel-demo-ingress.yaml
- otel-demo-grafana-ingress.yaml
- otel-demo-middleware.yaml
